# Generated by Django 4.0.5 on 2022-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='NAME')),
                ('price', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='CATEGORY')),
                ('release_date', models.CharField(blank=True, max_length=100, verbose_name='RELEASE_DATE')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
