# Generated by Django 4.0.5 on 2022-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='이미지명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='발매일'),
        ),
    ]
