# Generated by Django 4.0.5 on 2022-06-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_name',
        ),
    ]
